### ISSUE TITLE
Permission to add to OOS Utils

### ISSUE THREAD

**Issue by martindsouza** [antonscheffer/as_sftp#1]
@antonscheffer can I add this code (may alter etc) to @oraopensource [OOS Utils](https://github.com/oraopensource/oos-utils)? If yes, I'll take this as full permission to copy the code, alter it, etc.

Thanks in advance.

**Comment by antonscheffer** [comment]
I published this code with the MIT-licence. As far as I understand that gives permission to do with code whatever you want, Change it, alter it, republish  it on OraOpenSource. But if you want an explicit  approval. Yes @martindsouza , you may add this code to @OraOpenSource
Anton
