### ISSUE TITLE
Problem with download

### ISSUE THREAD

**Issue by seek78** [antonscheffer/as_sftp#11]
Hi, after a successful connection all downloaded files result zero-length.
Any advice?
Thanks

**Comment by seek78** [comment]
UP :-)

**Comment by McMogan** [comment]
Hi Seek, 
Have you tried to debug the dbms_lob.getlength( l_file ) in the get_file function to check where the problem come from (SFTP transfert or wrinting file in Oracle Dir ?

**Comment by antonscheffer** [comment]
I can't reproduce this problem with the information you have supplied :)

**Comment by seek78** [comment]
> Hi Seek, Have you tried to debug the dbms_lob.getlength( l_file ) in the get_file function to check where the problem come from SFTP transfert or writing file in Oracle Dir ?

Hi McMorgan, the OracleDir is ok, otherwise the file cannot be created.
I'll try to get the info you ask.

**Comment by McMogan** [comment]
I think the issue is at line 3569, because the return of get_file is not tested. So even if the function return false, the file will be created

```
function get_file( i_path varchar2, i_directory varchar2, i_filename varchar2 )
  return boolean
  is
    l_file blob; 
    l_rv boolean;
    l_fh utl_file.file_type;
    l_len pls_integer := 32767;
  begin
    l_rv := get_file( i_path, l_file ); -- l_rv IS NOT TESTED
    l_fh := utl_file.fopen( i_directory, i_filename, 'wb' );
```
In my version of the function I added 
```
l_rv := get_file( i_path, l_file );
IF NOT l_rv   THEN RAISE_APPLICATION_ERROR(-20099, 'Erreur dans la récupération du fichier'); END IF; 
```

**Comment by McMogan** [comment]
I meant that there should be an error in the logs (debug_msg) because the function get_file return FALSE for any error, then the file is created on oracle Directory with l_fh := utl_file.fopen( i_directory, i_filename, 'wb' );
So I think seek should put a g_log_level > 1 and check the logs, I think he should have a "get_file: not opened"
That's why I placed a l_rv test and a RAISE_APPLICATION_ERROR so I can be sure that any problem will stop my calling processes

```
function get_file( i_path varchar2, i_file in out nocopy blob )
..
if utl_raw.substr( l_buf, 1, 1 ) = SSH_FXP_STATUS
      then
        debug_msg( 'get_file: not opened' );
        l_idx := 2;
        get_int32( l_idx, l_buf, l_dummy ); -- id
        get_int32( l_idx, l_buf, l_dummy ); -- reason code
        get_string( l_idx, l_buf, l_buf2 );
        debug_msg( utl_i18n.raw_to_char( l_buf2, 'AL32UTF8' ) );
        exit;

```

**Comment by antonscheffer** [comment]
With the default setting of log_level I think those debug_messages should be visible in the dbms_output.
(I need to change that sometime, those messages shouldn't be in the "default" setting. And log_level and the level info, error and debug uses is wrong too :) )

**Comment by abaynehm** [comment]
Hi Anton

I have same problem with get_file getting zero length.

Any update to resolve the issue?

Thanks

**Comment by antonscheffer** [comment]
No, because I still don't what the cause of the issue is.
It suspect that it might be an (Unix) rights issue, the "Oracle" user can't read the files. But I'm not sure as I don't get any feedback on this.

**Comment by abaynehm** [comment]
It worked

I was passing only the folder excluding the file name for the i_path parameter

Thank you for your reply

Thanks

**Comment by balajivamshi** [comment]
Hi,

I'm getting an error where I'm able to fetch the file but the content in the file is being replaced with the 'ls' command of that file. Not sure whether it is 'ls' command or the hidden file content - (.) file - The content is - r .              ..            qùsftp_out      r!test1.txt   . 

Has anyone encountered this issue? If not - Any update to resolve this issue?

Thanks in advance.

**Comment by balajivamshi** [comment]
> Hi,
> 
> I'm using the Inbound SFTP - where I'm trying to get a file from the client-server. I'm getting an error where I'm able to fetch the file but the content in the file is being replaced with the 'ls' command of that file. Not sure whether it is the 'ls' command or the hidden file content - (.) file - The content is - r . � .. qùsftp_out r!test1.txt .
> 
> Has anyone encountered this issue? If not - Please provide me the advice to resolve this issue.
> 
> Thanks in advance.

I've got the solution - I just need to change the i_directory path to amend file_name to it - It worked!
