### ISSUE TITLE
First attempt to open connection failed

### ISSUE THREAD

**Issue by PeterNosko** [antonscheffer/as_sftp#14]
I installed this package in an existing oracle (19.13) account that already has all the needed ACLs/ACEs for sftp. I tried to check if I could just open a connection. My server name is masked here, but the script has the fully-qualified host name.

`begin
  as_sftp.open_connection( i_host => '***********' , i_trust_server => true );
  as_sftp.close_connection;
end;
/
`

Do you know what might be causing this error?

everything closed
try to connect to ***********, port 22
ORA-06512: at "SYS.UTL_TCP", line 19
ORA-06512: at "SYS.UTL_TCP", line 295
ORA-06512: at "AS_SFTP", line 1717

everything closed
everything closed

PL/SQL procedure successfully completed.

**Comment by antonscheffer** [comment]
I would first double check the ACL (port 22 open?). If the ACL is correct I would check if the SFTP server can reached from the database server, no firewall in between? Else I don't have a clue :)

**Comment by PeterNosko** [comment]
Yes, the ACL is * with no port limits, and the privileges are resolve and connect. I have a commercial Java-based SFTP installed for the same Oracle account and it connects just fine.

**Comment by antonscheffer** [comment]
Does that Java-based SFTP client run on the database server or on your client machine?

**Comment by PeterNosko** [comment]
In the database. It is OraSFTP. I installed as_sftp in the same schema, the one with the network privileges.

**Comment by PeterNosko** [comment]
I have the Java code, its package wrapper and as_sftp compiled in schema "A". The ACL/ACEs are granted to schema "B", where the code is being executed from. I think what I'm seeing is that the Java permissions work separately/differently. When I moved as_sftp to schema "B", I was able to get the connection.
