### ISSUE TITLE
Login with RSA Key and Passphrase

### ISSUE THREAD

**Issue by PeterNosko** [antonscheffer/as_sftp#15]
I am able to connect with userid/password. I followed your example in issue #12, additionally adding a i_passphrase parameter. It fails with `ORA-20030: Could not login.` I removed the passphrase from the private key and then it authenticated successfully.

Is the use of passphrases supposed to work?

**Comment by antonscheffer** [comment]
Depends on the key format used. I t doesn't work for the openssh-format. It takes 30-60 seconds to decode a key a that format, so I decided to not include that.
