### ISSUE TITLE
rsa-sha2-256 for login

### ISSUE THREAD

**Issue by serravin** [antonscheffer/as_sftp#18]
Hi Anton

Thank you very much for your quick feedback. Your solution (listed below) worked.

Is the link still up to date? "https://www.paypal.com/paypalme/apexplugins/10"

This might work
Change write_rsa_pk to
    function write_rsa_pk( p_pk_parameters tp_pk_parameters, p_hash_type pls_integer )
    return boolean
    is
      l_rv boolean;
      l_buf3 raw(3999);
      l_buf5 raw(3999);
      l_algo varchar2(100);
    begin
      if p_pk_parameters.count = 0
      then
        return false;
      end if;
      l_buf2 := null;
      l_algo := case p_hash_type
                  when HASH_SH256 then 'rsa-sha2-256'
                  when HASH_SH512 then 'rsa-sha2-512'
                  else 'ssh-rsa'
                end;
      append_string( l_buf2, utl_i18n.string_to_raw( l_algo, 'US7ASCII' ) );
      append_mpint( l_buf2, p_pk_parameters(2) );
      append_mpint( l_buf2, p_pk_parameters(1) );
      l_rv := write_pk( l_algo, l_buf2, null );
      if not l_pk_OK
      then
        return l_rv;
      end if;
      append_string( l_buf3, g_session_id );
      append_byte( l_buf3, l_buf );
      l_buf3 := powmod( utl_raw.concat( '01'
                                      , utl_raw.copies( 'FF'
                                                      , utl_raw.length( p_pk_parameters(1) )
                                                      - case p_hash_type
                                                          when HASH_SH256 then 54
                                                          when HASH_SH512 then 86
                                                          else 38
                                                        end
                                                      - case when utl_raw.substr( p_pk_parameters(1), 1, 1 ) = '00' then 1 else 0 end
                                                      )
                                      , case p_hash_type
                                          when HASH_SH256 then '003031300D060960864801650304020105000420' -- fixed ASN.1 value SHA256
                                          when HASH_SH512 then '003051300d060960864801650304020305000440' -- fixed ASN.1 value SHA512
                                          else '003021300906052B0E03021A05000414' -- fixed ASN.1 value SHA1
                                        end
                                      , dbms_crypto.hash( l_buf3, p_hash_type )
                                      )
                      , p_pk_parameters(3)
                      , p_pk_parameters(1)
                      );
      append_string( l_buf5, utl_i18n.string_to_raw( l_algo, 'US7ASCII' ) );
      append_string( l_buf5, l_buf3 );
      return write_pk( l_algo, l_buf2, l_buf5 );
    end;
 
 
And the call to that:
      l_rv := case utl_raw.cast_to_varchar2( l_pk_parameters(0) )
                 when 'RSA' then    write_rsa_pk( l_pk_parameters, HASH_SH1 )
                                 or write_rsa_pk( l_pk_parameters, HASH_SH256 )
                                 or write_rsa_pk( l_pk_parameters, HASH_SH512 )
                 when 'EC' then write_ec_pk( l_pk_parameters )
                 when 'DSA' then write_dsa_pk( l_pk_parameters )

Regards
Vincenzo

**Comment by antonscheffer** [comment]
Glad that the solution worked. The paypal link should work. But I have
never used it myself (and didn't receive any donations the last couple of
years). You should be able to change the amount if you wish.

Regards,
 Anton
