### ISSUE TITLE
Get-Put file from Oracle Directory

### ISSUE THREAD

**Issue by arintaphon** [antonscheffer/as_sftp#2]
@antonscheffer Could you suggest me about transferring data from Oracle directory and sFTP server? From your sample, it work fine to create spreadsheet but I don't know how to get-put file.

**Comment by antonscheffer** [comment]
You mean read a file from a Oracle directory into a blob, which you can transfer to a SFTP server using this package?
declare
  l_bfile  bfile;
  l_blob   blob;
  l_dest_offset integer := 1;
  l_src_offset  integer := 1;
begin
  as_sftp.open_connection( i_host => 'localhost' );
  as_sftp.login( i_user => 'demo', i_password => 'demo' );
  dbms_lob.createtempoorary( l_blob, true );
  l_bfile := bfilename( 'MY_DIR', 'test.txt' );
  dbms_lob.fileopen( l_bfile, dbms_lob.file_readonly );
  dbms_lob.loadblobfromfile
    ( dest_lob    => l_blob
    , src_bfile   => l_bfile
    , amount      => dbms_lob.lobmaxsize
    , dest_offset => l_dest_offset
    , src_offset  => l_src_offset
    );
  as_sftp.put_file( i_path => 'test.txt', i_file => l_blob );  
  dbms_lob.freetemporary( l_blob );
  dbms_lob.fileclose(l_bfile);
  as_sftp.close_connection;
end;

**Comment by arintaphon** [comment]
@antonscheffer Yes, that's the one I try to do so long time ago
Now I use your sample script to put file on sFTP and it's work! But I still can't get file from sFTP to my directory. Can you suggest me more?

**Comment by antonscheffer** [comment]
Use google, for instance https://oracle-base.com/articles/9i/export-blob-9i
