### ISSUE TITLE
Problem with open_connection

### ISSUE THREAD

**Issue by harrisadou** [antonscheffer/as_sftp#20]
Hello ,
I have an error with as_sftp.open_connection.
-- my code is :

begin
as_sftp.open_connection( i_host => ‘myhost’, i_port => 2222 , i_trust_server => true);
  dbms_output.put_line('login');    
  as_sftp.login( i_user => 'mysuser', i_password =>'mypass' ) ;
  as_sftp.close_connection;
end;

Rapport d'erreur -
ORA-29259: fin d'entrée atteinte
ORA-06512: à "SYS.UTL_TCP", ligne 94
ORA-06512: à "SYS.UTL_TCP", ligne 322
ORA-06512: à "SYS.UTL_TCP", ligne 385
ORA-06512: à "HR.AS_SFTP", ligne 1462
ORA-06512: à "HR.AS_SFTP", ligne 1710
ORA-06512: à "HR.AS_SFTP", ligne 2413
ORA-06512: à "HR.AS_SFTP", ligne 4468
ORA-06512: à "HR.AS_SFTP", ligne 4511
ORA-06512: à ligne 3
29259. 00000 -  "end-of-input reached"
*Cause:    The end of the input was reached.
*Action:   If the end of the input is reached prematurely, check if the input
           source terminates prematurely.  Otherwise, close the connection
           to the input.
everything closed

**try to connect to XXXXX (my_host) , port 2222
SSH-2.0-mod_sftp/0.9.9
using aes128-cbc, aes128-cbc
using hmac-sha1, hmac-sha1
using ssh-dss
using diffie-hellman-group14-sha1**

when i add i_excluded_kex_algos => 'diffie-hellman-group14-sha1,diffie-hellman-group14-sha256' 
i have : 

**try to connect to (my host ...... ) , port 2222
SSH-2.0-mod_sftp/0.9.9
using aes128-cbc, aes128-cbc
using hmac-sha1, hmac-sha1
using ssh-dss
using diffie-hellman-group1-sha1**

**I tested on another SFTP host in port 2 and it works.**

I don't undestand why on port 2222 it doesn't work.

Can you help me please.

Thank you.

**Comment by harrisadou** [comment]
when i use i_excluded_kex_algos => 'diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group1-sha1'

i have : 
**try to connect to (my host .... ) , port 2222
SSH-2.0-mod_sftp/0.9.9
using aes128-cbc, aes128-cbc
using hmac-sha1, hmac-sha1
using ssh-dss
using diffie-hellman-group-exchange-sha1**

**Comment by antonscheffer** [comment]
Seems like a bug in the SFTP server mod_sftp/0.9.9. (= ProFTPD 1.3.5 ?)
Using  i_excluded_pkey_algos => 'ssh-dss' with as_sftp.open_connection solves the problem.
