### ISSUE TITLE
Uploading the file partially

### ISSUE THREAD

**Issue by VipinVince** [antonscheffer/as_sftp#27]
Hi 

We have been using your SFTP package since 2011, and it works well with almost all of our servers, including PPK keys.

When we use put_file for sending a 5mb file to one of the servers (sftp.server_1.com), the file gets received partially around 200kb.

Debugging throws the exception from read_fxp_message exactly from the below line
put_file >read_fxp_message>**p_buf := utl_raw.substr(p_buf, 5)**

select utl_raw.substr('00000020', 5) from dual
ORA-06502: PL/SQL: numeric or value error

Please note that the same file can to sent without any issue to one of the other server(mft.server_2.com) . Attached both logs for your verification.
[log_server_1.txt](https://github.com/antonscheffer/as_sftp/files/15009552/log_server_1.txt)
[log_server_2.txt](https://github.com/antonscheffer/as_sftp/files/15009553/log_server_2.txt)

I would greatly appreciate any assistance you can provide

**Comment by antonscheffer** [comment]
You could try changing a part in read_fxp_message:
          -- skip length attribute
          if utl_raw.length( p_buf ) > 4
          then
            p_buf := utl_raw.substr( p_buf, 5 );
          else
            p_buf := null;
          end if;
          while coalesce( utl_raw.length( p_buf ), 0 ) < l_len
          loop
            read_fxp_message( l_buf, false );
            p_buf := utl_raw.concat( p_buf, l_buf );
          end loop;
