### ISSUE TITLE
Idea/question: Reverse order of writing rsa_pk?

### ISSUE THREAD

**Issue by franz-ap** [antonscheffer/as_sftp#28]
Hello Anton,

Thank you very much for sharing this package!
It works fine.

Would it make sense to reverse the order of writing rsa_pk (line 3616-3618 in as_sftp.pkb) from _weakest_to_strongest_ to _strongest_to_weakest_?
I saw this message in an sftp server log:
   _userauth_pubkey: signature algorithm ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]_
No big deal. I was just trying to avoid that message and wanted to share the idea. But I am not an expert.

Best regards
Franz

**Comment by antonscheffer** [comment]
If I change that order you will get rid of the warning message.
But anyone using a SFTP server which doesn't support rsa-sha2-256 and rsa-sha2-512 will get two warning messages.
I have no idea how many people are using this package.
And I have even less idea of the capabilities of the servers they are trying to connect to.
So it's impossible for me to tell if this is a good idea or not,
