### ISSUE TITLE
Oracle Autonomous Transaction Processing (ATP) and Compute Instance sftp

### ISSUE THREAD

**Issue by SoftPath-inc** [antonscheffer/as_sftp#7]
I am trying to sftp files between an Oracle ATP instance and an Oracle Compute Instance sftp server using your package.  It will open and close the connection without generating an error, but will not login. The error is ORA-29260 network error: not connected when executing as_sftp.login. (Also Ora-6512 Lines 168 and 341 in SYS.UTL_TCP.

I am using the Oracle Console network security list for authorizing access to the sftp server, not a software firewall on the sftp server.  The sftp server will accept all connections from the internal Oracle network. Oracle ATP does not give an IP address.

Any suggestions?

Thanks!

**Comment by antonscheffer** [comment]
Might have something to do with "Restrictions for Database PL/SQL Packages", see https://docs.oracle.com/en/cloud/paas/atp-cloud/atpug/experienced-database-users.html#GUID-829A7D07-1EA4-4F59-AA60-F780FABAFDEC

**Comment by SoftPath-inc** [comment]
Looks like you are correct, UTL_TCP is removed from Oracle ATP.  Any suggestions?
Thanks for the quick response!
Joe

**Comment by antonscheffer** [comment]
Complain with Oracle :) My package really need utl_tcp.

**Comment by SoftPath-inc** [comment]
I can do that 😊

Thanks
Joe
