### ISSUE TITLE
Incorrect signature verification for ssh-dss

### ISSUE THREAD

**Issue by McMogan** [antonscheffer/as_sftp#9]
Hi Anton,

There is a problem in **validate_signature** for ssh-dss when the l_dss_r start with '00' (1% of my connexions to 1 sftp server) because demag is returning  LTRIM( rv, '0')

```
PROCEDURE validate_signature
l_v := demag( xmod( xmod( rmul( mag( powmod( l_g, l_u1, l_p ) ), mag( powmod( l_y, l_u2, l_p ) ) ), mag( l_p ) ), mag( l_q ) ) );
      IF l_v != l_dss_r
      THEN
        RAISE_APPLICATION_ERROR( -20012, 'ssh-dss NOT OK' );
      END IF;
```

I made this correction in my code (can't use LTRIM on l_dss_r because l_v and l_dss_r are RAW, and demag returning a VARCHAR)
`l_v := LPAD(demag( xmod( xmod( rmul( mag( powmod( l_g, l_u1, l_p ) ), mag( powmod( l_y, l_u2, l_p ) ) ), mag( l_p ) ), mag( l_q ) ) ), 40, '0');
`      
 
Regards
Morgan

**Comment by antonscheffer** [comment]
Fixed it, thanks for reporting (and solving) that problem.

**Comment by McMogan** [comment]
You made such a great job with this package, it's a pleasure to help.
